version: "3.7"

services:
  eip-backend:
    image: eip-backend:latest
    container_name: eip-backend
    restart: always
    depends_on:
      - mongodb
    # ports:
    #   - "5000:5000"
    networks: 
      - eip-network
  
  #TODO:how to correct CORS error (temp running outside docker network)
  energy-information-platform:
    image: energy-information-platform:latest
    depends_on:
      - eip-backend
    networks: 
      - eip-network
    links:
      - eip-backend
    ports:
      - "8080:8080"
  mongodb:
    # image: mongodb-raspberrypi4-unofficial-r7.0.4
    image: mongo:6-jammy
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tal      
      - MONGO_INITDB_ROOT_PASSWORD=tal
      - MONGO_INITDB_DATABASE=clients
    networks: 
      - eip-network
    ports:
      - '27017:27017'
    volumes:
      - type: volume
        source: MONGO_DATA
        target: /data/db
      - type: volume
        source: MONGO_CONFIG
        target: /data/configdb
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongodb
    networks: 
      - eip-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=tal
      - ME_CONFIG_MONGODB_ADMINPASSWORD=tal
      - ME_CONFIG_BASICAUTH_USERNAME=tal
      - ME_CONFIG_BASICAUTH_PASSWORD=tal
    ports:
      - '8081:8081'

volumes:
  MONGO_DATA:
    name: MONGO_DATA
  MONGO_CONFIG:
    name: MONGO_CONFIG

networks:
  eip-network:
    driver: bridge